/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6c10cec9-f4a0-44bc-8d93-cfb7e37caf57",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SjEIup5zK",
    "aws_user_pools_web_client_id": "6mk77fr4jpinm1lm941ki4ohp4",
    "oauth": {}
};


export default awsmobile;
